### ISSUE TITLE
Testing Exceptions  

### ISSUE THREAD

**Issue by mjp59** [mjp59/bme590hrm#2]
In line 29 of test_heartrate.py I am trying to test a exception for file not found. What is the best way to go about this?

**Comment by mlp6** [comment]
Can you paste a hyperlink the specific line of code?  Not sure what branch I should be looking for `test_heartrate.py`.  I may also expand this question to the `#python` Slack channel as it may have broader appeal to the class (once I see what you code is trying to do).

**Comment by mjp59** [comment]
https://github.com/mjp59/bme590hrm/blob/9413b8feeff2db2e2511b6274cdc22e514bcd818/test_heartrate.py#L32-L40

That should be the link to the code.

**Comment by mlp6** [comment]
Great; I've added @suyashkumar to this to make sure that we provide a response consistent with what he went over in lecture last week.  I would potentially approach this a tad differently than you have outlined, so I just want to confirm that he and I are on the same page.  Stay tuned.

**Comment by suyashkumar** [comment]
@mjp59 hi there! I think that your test seems to have the right idea but your underlying code in `heartrate.py` may need some modifications.

Generally, in this scenario it seems like you want `read_my_file` to raise a `FileNotFoundError`. As your code stands right now (reproduced below) `read_my_file` will not raise this error, it will catch it (in the except block) print a message and exit.

https://github.com/mjp59/bme590hrm/blob/9413b8feeff2db2e2511b6274cdc22e514bcd818/heartrate.py#L69-L94

Likely what you want to do is let this `FileNotFoundError` propogate up to the caller for your `read_my_file` function. This is because you want the caller (in this case `main`) to decide how to deal with the FileNotFoundException. That is, `read_my_file` is not the thread of logic responsible for communicating with the user, or not even the thread of logic responsible for determining why the file was even read in the first place--`main` is. This means you probably want this error to be handled by `main` because `main` will know what to do if the file is unable to be found. In this case, you may want to print a message to the user and exit. However, in another place (if any) you might use `read_my_file` you may want to do something different if a file is not found. This is why you would want the caller of the `read_my_file` function to handle what happens. 

In this case you can either 
a. remove the try/catch in the `read_my_file` function and add one around it in `main` OR
b. simply re `raise` the exception in `read_my_file`'s except. You can do something like:

```py
     try:
         # stuff
     except FileNotFoundError as err:
          logging.error('File not found in the directory') 
          raise err
```

**Comment by mjp59** [comment]
Thanks Suyash! I didn't realize catching the exception causes it not to be raised. Re-raising it worked.
